version: '3'

services:
  web:
    build: .
    container_name: TrueORFalseGPT
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /mysite
    ports:
      - 8000:8000
    volumes:
      - .:/mysite
    # ポート待受とかしていないコンテナの場合、trueに設定しておくとコンテナが起動し続けます
    tty: true