version: '3'

services:
  web:
    build: .
    container_name: TrueORFalseGPT
    # requirements.txtではopenaiとpsycopg,langchainが読み込めないため
    command: bash -c "pip3 install langchain openai && pip3 install psycopg && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    working_dir: /mysite
    ports:
      - 8000:8000
    volumes:
      - .:/mysite
    # ポート待受とかしていないコンテナの場合、trueに設定しておくとコンテナが起動し続けます
    tty: true
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
